<?php

namespace Equinoxe\DataStoreBundle\Entity\Orm;

/**
 * Test class for StringRecord.
 * Generated by PHPUnit on 2011-01-18 at 15:50:48.
 */
class StringRecordTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var StringRecord
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new StringRecord;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @todo Implement testGetValue().
     */
    public function testGetValue() {
        $this->object->setValue('testVal');
        $this->assertEquals('testVal', $this->object->getValue());
    }
}
